module.exports = {
  ROOT: '/',
  LOGIN: '/login',
  LOGOUT: '/logout',
  SIGNUP: '/signup',
  USERS: '/users',
  USER_ID: '/:user_id',
  STOCK_DETAILS: '/stock-details',
  KEYWORD: '/:keyword',
  SYMBOL: '/:symbol',
  INTERVAL: '/:interval',
  COMPANY_PROFILES: '/company-profiles',
  RECOMMENDATION_STOCK_LIST: '/recommendation-stock-list',
  VIEWS: '/views',
  HITS: '/hits',
  TRENDING: '/trending',
  PORTFOLIO: '/portfolio',
  PORTFOLIOS: '/portfolios',
  RANDOM: '/random',
  CURRENT_USER: '/current-user',
  PREFERENCE_INFOS: '/preference-infos',
  PREFERENCE_INFO_ID: '/:preference_info_id',
  PORTFOLIO_ITEMS: '/portfolio-items',
  PORTFOLIO_ITEM_ID: '/:portfolio_item_id',
  RECOMMENDATIONS: 'recommendations',
  PREFERENCE: 'preference',
};
